### ISSUE TITLE
Implement clever compression logic

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/disk-objectstore#14]
- [ ] For instance trying to compress, but storing uncompressed if the resulting compression ratio is below a given user-defined threshold.
- [ ] Allow also to do heuristics for this part, e.g. compressing only 10% of the file in small chunks (% and chunk size could be specified by the user).
- [ ] Also allow to specify compression level as an option, rather than hardcoded.

For backward compatibility, one could set the `compress` flag to be a dictionary (or a class instance) that contains all the information needed, e.g. compression threshold, compression level, compression_heuristics_percentage, ...)

**Comment by dev-zero** [comment]
>     * [ ]  For instance trying to compress, but storing uncompressed if the resulting compression ratio is below a given user-defined threshold.

AFAIK that's something modern compression algorithms already do (see the various tuning knobs of LZMA/LZ4/XZ), if possible use one of those as they usually already provide multithreaded implementations.

>     * [ ]  Allow also to do heuristics for this part, e.g. compressing only 10% of the file in small chunks (% and chunk size could be specified by the user).
> 
>     * [ ]  Also allow to specify compression level as an option, rather than hardcoded.
> 
> 
> For backward compatibility, one could set the `compress` flag to be a dictionary (or a class instance) that contains all the information needed, e.g. compression threshold, compression level, compression_heuristics_percentage, ...)

The other thing is: given the use case for the objectstore I'd probably go for a compression algorithm with very good decompression and not so good compression speed. And having a bit-rot-detection feature might also be interesting.

**Comment by giovannipizzi** [comment]
Thanks for the very useful comments!
Will look into that.
Regarding the bit-rot detection feature, do you have a link explaining more in detail what you mean (or which libraries/compression algorithms already implement it?)

Final question, for the advanced algorithms you mention, are these already part of standard python (e.g. [in this module](https://docs.python.org/3/library/lzma.html)) or one needs some additional dependencies?

**Comment by dev-zero** [comment]
> Thanks for the very useful comments!
> Will look into that.
> Regarding the bit-rot detection feature, do you have a link explaining more in detail what you mean (or which libraries/compression algorithms already implement it?)

In principle you can have occasional bit-flips in data. While there are some filesystems which have checksums (recent versions of XFS and ext4) they're not necessarily activated. Some compression algorithms/libs allow to integrate checksums and/or additional data to recover. See for example the manpage of `xz` (`--check` option).

> Final question, for the advanced algorithms you mention, are these already part of standard python (e.g. [in this module](https://docs.python.org/3/library/lzma.html)) or one needs some additional dependencies?

I guess some of them are additional modules (like Snappy).

**Comment by dev-zero** [comment]
Ok, the more I think about it, the less appealing is the idea of compressing single files:

* what are the statistics of the filesizes in AiiDA? My guess would be that all code input files are below 4K, meaning that there is no point in compressing them while being single files (4K being the usual filesystem block size). This of course being different when you start writing multiple files with content less than 4K to a common packfile.
* many files (including output files) likely have similar content, meaning that if you'd compress them together into a pack, you'd end up with a much better compression ratio (and given todays architectures likely better access times: I/O vs on-the-fly decompression), this could be improved by using metadata provided by AiiDA (like origin of the data) to build efficient packs, meaning that you wouldn't base your packs on hashes or uuids anymore

**Comment by giovannipizzi** [comment]
Thanks for the comment! We can have some stats on real DBs, I'll be looking into it as some point. 
(I also thought that .zip does this, i.e. zipping each file individually?)

However, the reason I had is to have fast random access to any single object.
Would it be possible when compressing multiple files together, to get efficiently only one of them without decompressing everything? 

I agree that one could find a compromise and zip together files from the same node, that are likely to get retrieved at the same time - but this then won't solve the issue of multiple similar input files in different nodes.

**Comment by giovannipizzi** [comment]
With the switch to using a hash as the key, data corruption can be detected by just checking the hash key.

I think I will solve this by making the compression algorithm a repository parameter and letting users choose the one they prefer depending on their needs.

**Comment by giovannipizzi** [comment]
Setting as nice-to-have because this can be added later in a non-backward compatible way

**Comment by zhubonan** [comment]
Following the discussion with @giovannipizzi today. I want to add here that file system with transparent compression uses heuristics to check if a file is compressible or not. 

We could use a similar idea when packing the loose file, e.g. only compress the ones that are compressible. Since the loose files are already on the disk, it should be possible to apply some of such heuristics. 

Note that switching compression/no-compression when reading a stream can be more complex, but it is only needed when adding an object directly to the pack. So this use case would be in low priority.

Here are some notes from the BTRFS documentation:
https://btrfs.readthedocs.io/en/latest/Compression.html#pre-compression-heuristics

The implementation is here:

https://elixir.bootlin.com/linux/latest/source/fs/btrfs/compression.c#L1376

From my very limited C knowledge, what it does seems to be :

1. Obtain a (small sized) sample of the data
2. Check the set size of the bytes present - this detects text files where the bytes are limited to a small size. https://elixir.bootlin.com/linux/latest/source/fs/btrfs/compression.c#L1275
3. Check the "core-size", e.g. the number of byte sets that covers 90% of the data, in order to detect structured binary files. 
4. Shannon entropy: https://elixir.bootlin.com/linux/latest/source/fs/btrfs/compression.c#L1101

Step 2-4 are in the increasing order of compute costs, and hence are performed in serial. If any passes, the check stops, and the data is considered as compressible.
